kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ss
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    namespace: ss
    name: ss2
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: ss2
      spec:
        containers:
        - name: ss2
          image: shadowsocks/shadowsocks-libev
          ports:
          - name: ss2
            containerPort: 9771
          command:
            - ss-server 
          args: [ "-s", "0.0.0.0", "-p", "9771", "-k", "TTsPESJz7nISrOTZ", "-m", "aes-256-cfb", "-t", "300"]
        - name: nginx
          image: nginx
          ports:
          - name: nginx
            containerPort: 80

- kind: Service
  apiVersion: v1
  metadata:
    namespace: ss
    name: ss2
  spec:
    type: LoadBalancer
    selector:
      app: ss2
    ports:
      - name: ss
        protocol: TCP
        port: 9771
      - name: nginx
        protocol: TCP
        port: 80
