kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
provisioner: nfs.int.parcelfuture.com/nfs
mountOptions:
  - vers=4.1
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs1
provisioner: 192.168.2.100/data
mountOptions:
  - vers=4.1
